name: NodeJS with Webpack

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 22.2.0
      uses: actions/setup-node@v3
      with:
        node-version: 22.2.0
    - name: Build
      run: |
        npm install
        npx webpack
